[files]
recent_files=/home/federico/Escritorio/UBA/tecnicas de diseño de algoritmos /cache_opt.cpp;/home/federico/Escritorio/UBA/tecnicas de diseño de algoritmos /pruebas_varias.cpp;/home/federico/Escritorio/funcionalidad para facturacion automatica.txt;/home/federico/.config/geany/snippets.conf;/home/federico/Escritorio/UBA/tecnicas de diseño de algoritmos /conf_build_para_geany;/home/federico/Escritorio/UBA/tecnicas de diseño de algoritmos /.gitignore;/mnt/Disco duro/Varios/Documentos/UBA/tecnicas de diseño de algoritmos /pilacauta_topdown.cpp;/home/federico/Escritorio/UBA/tecnicas de diseño de algoritmos /optipago.cpp;/home/federico/Escritorio/UBA/tecnicas de diseño de algoritmos /SumaSubconjuntosBT.cpp;/home/federico/Documentos/automatizar-facturacion-arca/prueba.py;
recent_projects=/home/federico/proyectos/tecnicas de diseño de algoritmos .geany;/home/federico/Escritorio/UBA/tecnicas de diseño de algoritmos /tecnicas de diseño de algoritmos .geany;/home/federico/Documentos/automatizar-facturacion-arca/automatizar-facturacion-arca.geany;/home/federico/Documents/automatizar-facturacion-arca/automatizar-facturacion-arca.geany;/home/federico/Documents/wayland-fuego/wayland-fuego.geany;/home/federico/Documents/cosas-wayland/cosas-wayland.geany;/home/federico/Documents/cosas_wayland/cosas_wayland.geany;/home/federico/Desktop/UBA/paradigmas de la programacion/paradigmas.geany;
current_page=0
FILE_NAME_0=0;C++;0;EUTF-8;0;1;0;%2Fhome%2Ffederico%2FEscritorio%2FUBA%2Ftecnicas%20de%20diseño%20de%20algoritmos%20%2Foperaciones_secuenciales_bottom_up.cpp;0;4

[project]
session_file=/home/federico/proyectos/tecnicas de diseño de algoritmos .geany
project_file_path=/home/federico/proyectos

[geany]
treeview_position=245
msgwindow_position=664
geometry=0;0;1920;1008;1;
sidebar_page=0

[VTE]
last_dir=/mnt/Disco duro/Varios/Documentos/UBA/tecnicas de diseño de algoritmos 

[search]
find_all_expanded=true
replace_all_expanded=true
position_find_x=846
position_find_y=628
position_replace_x=987
position_replace_y=383
position_fif_x=432
position_fif_y=370

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=/usr/lib/x86_64-linux-gnu/geany/autoclose.so;/usr/lib/x86_64-linux-gnu/geany/lsp.so;/usr/lib/x86_64-linux-gnu/geany/debugger.so;/usr/lib/x86_64-linux-gnu/geany/splitwindow.so;/usr/lib/x86_64-linux-gnu/geany/geanydoc.so;
